### ISSUE TITLE
Idea: layer in JOSM

### ISSUE THREAD

**Issue by Kilkenni** [Foxhind/MapCraft#86]
Idk if this idea has been proposed before. Perhaps it would be useful to implement a MapCraft plugin. I guess it would be nice to see info for slices as a layer in JOSM: borders, status, maybe usernames. Thus the user will be able to see where his slice ends without switching between MapCraft and JOSM every now and then.

**Comment by Kilkenni** [comment]
There is a WMS link in MapCraft, but I don't know how to use it.

**Comment by DaCor1** [comment]
It's broken

**Comment by Foxhind** [comment]
Fixed!
