### ISSUE TITLE
Pie isn't working

### ISSUE THREAD

**Issue by Semigradsky** [Foxhind/MapCraft#90]
http://mapcraft.nanodesu.ru/pie/630

Errors in console:
```
Error: <rect> attribute x: Expected length, "NaN".
Error: <rect> attribute width: Expected length, "NaN".
```

Error in chat after load pie:
> Failed to load pie information

Errors in chat after click to pieces:
> Failed to find piece with index: 14
> Piece index looks too big: 125 may be old cake was cached. Try Ctrl-F5

**Comment by Foxhind** [comment]
Fixed. Just troubles on server after updates.
