### ISSUE TITLE
Пирог не отображается на карте

### ISSUE THREAD

**Issue by romanshuvalov** [Foxhind/MapCraft#91]
Почему на карте нет пирога?
Пирог: http://mapcraft.nanodesu.ru/pie/698
Карта: http://mapcraft.nanodesu.ru/map?zoom=10&lat=7066305.80111&lon=5734480.72078&layers=BT

Полагаю, многих других тоже нет, это баг или фича?

**Comment by altair86** [comment]
Отображается норм
